version: '3.7'

x-env-defaults: &env
  NEW_RELIC_ENABLED: ${NEW_RELIC_ENABLED-0}
  NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY-(unset)}
  NODE_ENV: development
  TERMINUS_TIMEOUT: 1000
  TERMINUS_SHUTDOWN_DELAY: 0
  YARN_CACHE_FOLDER: /.yarn-cache

x-node-defaults: &node
  tty: true
  init: true
  image: node:14.13-alpine
  working_dir: /oleic
  restart: always
  volumes:
    - .:/oleic:cached
    - ./node_modules:/oleic/node_modules:delegated
    - yarn-cache:/.yarn-cache
  environment:
    <<: *env

services:
  commands:
    <<: *node
    entrypoint: ["tail"]
    command: ["-f", "/dev/null"]

  app:
    <<: *node
    working_dir: /oleic/app
    entrypoint: ["yarn"]
    command: ["dev"]
    environment:
      <<: *env
      BROWSER_GRAPHQL_URI: http://server.highsoy.com:53190/graphql
    depends_on:
      - server
    ports:
      - "53191:53191"
    hostname: app.highsoy.com

  server:
    <<: *node
    working_dir: /oleic/server
    entrypoint: ["yarn"]
    command: ["dev"]
    environment:
      <<: *env
      APP_HOST: ${APP_HOST-app.highsoy.com:53191}
      GOOGLE_GEOCODE_API_KEY: ${GOOGLE_GEOCODE_API_KEY-}
      MONGO_URI: ${PM_MONGO_URI-mongodb://root:password123@mongodb-primary:27017,mongodb-secondary:27017/?replicaSet=unitedsoybean&authSource=admin&readPreference=primary}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY-notset}
    ports:
      - "53190:53190"
    depends_on:
      - mongodb-secondary
    hostname: server.highsoy.com
    networks:
      default:
        aliases:
          - server.highsoy.com

  mongodb-primary:
    image: bitnami/mongodb:4.0
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=unitedsoybean
    volumes:
      - mongodb_primary:/bitnami
    ports:
      - "58123:27017"

  mongodb-secondary:
    image: bitnami/mongodb:4.0
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=unitedsoybean
    volumes:
      - mongodb_secondary:/bitnami

volumes:
  yarn-cache: {}
  mongodb_primary: {}
  mongodb_secondary: {}
